### ISSUE TITLE
Install erdantic in windows

### ISSUE THREAD

**Issue by bytelinker** [drivendataorg/erdantic#111]
Hello,

the installation of erdatic is breaking, there are some posts, but I can't find a solution, till know. Any advice how to fix this, please? Actual graphiz is installed in default path.

Thanks bytelinker

      building 'pygraphviz._graphviz' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\pygraphviz
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DSWIG_PYTHON_STRICT_BYTE_CHAR -DGVDLL -IC:\software\Python311\include "-Ic:\Program Files\Python311\include" "-Ic:\Program Files\Python311\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win-amd64-cpython-311\Release\pygraphviz/graphviz_wrap.obj
      graphviz_wrap.c
      pygraphviz/graphviz_wrap.c(3020): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "graphviz/cgraph.h": No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by jayqi** [comment]
Hi @bytelinker,

Based on what you're showing, I believe that your issue is with the installation of pygraphviz, which is one of erdantic's dependencies. I recommend that you take a look at [pygraphviz's installation documentation](https://pygraphviz.github.io/documentation/stable/install.html)(they have a section specifically calling out Windows), and open an issue on the [pygraphviz repository](https://github.com/pygraphviz/pygraphviz/issues) if you have further issues.

**Comment by jayqi** [comment]
Hi @bytelinker,

I'm going to close this issue for now. If you're able to first get `pip install pygraphviz` or `conda install pygraphviz -c conda-forge` to work, but you still continue to have an error installing erdantic, then please let me know and I can reopen the issue.
