### ISSUE TITLE
Follow edges in a graph automatically

### ISSUE THREAD

**Issue by adsharma** [drivendataorg/erdantic#28]
test case:

https://github.com/adsharma/fquery/blob/master/tests/mock_user.py

Right now, I get only one class in the diagram, namely: MockUser. Would like to see "friends" and "reviews" edges/objects in the output.

**Comment by jayqi** [comment]
Hi @adsharma, thanks for trying out erdantic!

If I'm understanding your code correctly, your package `fquery` extends stock `dataclasses` with additional graph relations (the `@node` and `@edge` decorators)? 

erdantic's `dataclasses` functionality will only work with what is part of `dataclasses`. There is no way to automatically parse the custom implementation of relations that you are adding. If you had written your `MockUser` class like this:

```
@dataclass
class MockUser:
    name: str
    age: int
    friends: List["MockUser"]
    reviews: List["MockReview"]
```

using only built-in `dataclasses` semantics, then erdantic should work as expected. 

If you would like to develop a custom erdantic integration for your package, you can take a look at our documentation ["Adding New Frameworks"](https://erdantic.drivendata.org/extending/).

**Comment by adsharma** [comment]
Thanks for the pointer. I'll take a look.

**Comment by adsharma** [comment]
https://github.com/adsharma/erdantic has code that works for fquery + a few stylistic changes that you and I disagree on. There are some fixes for passing tests on Linux systems that you might be interested in.
