### ISSUE TITLE
Add extra Column

### ISSUE THREAD

**Issue by Lazloo** [drivendataorg/erdantic#70]
Hey, 

I would like to display also the description and also other attributes of a column in extra columns. Is this possible with ERDANTIC?

**Comment by paultrh** [comment]
It seems that everything goes throw the dot language and the [html node types](https://graphviz.org/doc/info/shapes.html)
As described in the documentation you can [add new frameworks](https://erdantic.drivendata.org/stable/extending/)

Based on it, you can inherit or create new rules.
In the code below, the already defined class for `pydantic` are overridden to add a third column description.
 
```python 
_row_template_custom = """<tr><td>{name}</td><td>{type_name}</td><td port="{name}">{description}</td></tr>"""
 
_table_template_custom = """
<<table border="0" cellborder="1" cellspacing="0">
<tr><td port="_root" colspan="3"><b>{name}</b></td></tr>
{rows}
</table>>
"""
 
 
class PydanticFieldCustom(PydanticField):
 
    def dot_row(self) -> str:
        description = self.description if self.description is not None else ' '
        return _row_template_custom.format(name=self.name, type_name=self.type_name, description=description)
 
 
@register_model_adapter("pydantic")
class PydanticModelCustom(PydanticModel):
 
    @property
    def fields(self) -> List[PydanticFieldCustom]:
        return [PydanticFieldCustom(field=f) for f in self.model.__fields__.values()]
 
    def dot_label(self) -> str:
        rows = "\n".join(field.dot_row() for field in self.fields)
        return _table_template_custom.format(name=self.name, rows=rows).replace("\n", "")
 ```

It gives a result like this:
<img width="357" alt="img" src="https://user-images.githubusercontent.com/8947658/201438965-91e4ba09-70ed-46fa-a4c5-a43b05e055d2.png">

**Comment by jayqi** [comment]
Noting here that the backend for erdantic has changed in v1.0. The above example will no longer work because `PydanticModel` and `PydanticField` no longer exist. 

Instead, I have documented a different example for adding a third column using the new backend design to the documentation [here](https://erdantic.drivendata.org/v1.0/extending/#example-adding-a-column-with-default-field-values).
