### ISSUE TITLE
Feature: Customizable graph label -> remove erdantic watermark

### ISSUE THREAD

**Issue by mansenfranzen** [drivendataorg/erdantic#78]
First of all, thanks for creating `erdantic` in the first place! I really like how it's possible to generate ERDs from pydantic models and ouput them via SVG.

I just really wish it would be possible to provide [custom labels](https://github.com/drivendataorg/erdantic/blob/c094337c79029d3d6cc530748b5fb80a46d58ab0/erdantic/erd.py#L120) for the resulting graphs. Or at least to provide a possibility to remove the erdantic watermark `Created by erdantic v0.5.0 <https://github.com/drivendataorg/erdantic>`. 

From my personal view, this is a drawback as it distracts the viewer from the main content. Moreover, it feels like the resulting diagram was generated with some shareware or free license of a proprietary software which requires self credits. Actual, the total opposite is the case because you've chosen MIT license (thanks for that!). I strongly believe that your package does not require the watermark and would enjoy even wider usage without it.

Currently, I hesitate to include it into `autodoc_pydantic` without any customization. @yves-renier has created a great [PR](https://github.com/mansenfranzen/autodoc_pydantic/pull/148) to leverage `erdantic` improving the auto-documentation of pydantic models.

I would be willing to provide a PR upstream adding this feature if you agree.

**Comment by jayqi** [comment]
Hi @mansenfranzen. Thanks for the feedback. As an immediate workaround without any changes to erdantic, you could generate the pygraphviz object and then modify its attributes to remove the label, or generate the graphviz DOT language specification of your graph, and modify the DOT to remove the label.

**Comment by mansenfranzen** [comment]
Hi @jayqi,

thanks for taking your time looking at this issue!

Regarding an immediate workaround, I'm feeling a bit reluctant to put any `pygraphviz` logic into `autodoc_pydantic` because it does not belong there. 

I would be more than happy to encapsulate everything required within `erdantic`. If possible, I'm happy to assist you but I know API design considerations take time ;-).

From my point of view, the `draw` and `to_dot` functions/methods should both support specifying the label. The `EntityRelationshipDiagram.graph` method generates the `pygraphviz` object and will require access to the label information. 

Actually while thinking about [`EntityRelationshipDiagram.graph`](https://github.com/drivendataorg/erdantic/blob/c094337c79029d3d6cc530748b5fb80a46d58ab0/erdantic/erd.py#L81), nothing can be configured for the `pygraphviz` object at the moment. I think it would be a great feature to pass an optional configuration dictionary to the `EntityRelationshipDiagram.graph` method to overwrite the default values passed to the [`pgv.AGraph`](https://github.com/drivendataorg/erdantic/blob/c094337c79029d3d6cc530748b5fb80a46d58ab0/erdantic/erd.py#LL113C13-L113C23) object instantiation. This would not only allow to overwrite the label but also all other attributes (such as font size, color, etc...). This would provide great flexibility to your users. What do you think? 

Coming back to the API consideration, the `draw` and `to_dot` functions/methods could support a new parameter named `graph_config` which communicates a clear purpose and is unambiguous in my opinion. Moreover, this approach will prevent bloating up the signatures of the `draw` and `to_dot` functions/methods for any future feature requests regarding the customizability of the [`pgv.AGraph`](https://github.com/drivendataorg/erdantic/blob/c094337c79029d3d6cc530748b5fb80a46d58ab0/erdantic/erd.py#LL113C13-L113C23) object.

**Comment by jayqi** [comment]
Hi @mansenfranzen,

Thanks for following up and for taking the time to look at the code and think about the design. 

I think your suggestion for supporting keyword arguments or a dictionary that is passed through to the `AGraph` instantiation makes sense. (My preference would be to name this something like `graph_kwargs`, which feels like it signposts what it is a little more explicitly.)

If you are willing to contribute a PR, that would be welcome.

**Comment by jayqi** [comment]
Hi @mansenfranzen,

Customizing the graph label is available in the new v1.0.0. This is currently a pre-release version (v1.0.0rc1), installable with `pip install erdantic --pre`. 

There are new `graph_attr`, `node_attr`, and `edge_attr` parameters on the `draw` and `to_graphviz` methods/functions to pass in these Graphviz attributes. They get merged into the respective mapping on the created Graphviz object. (`to_graphviz` is the replacement for the old `graph` property`.)

You can see documentation regarding this functionality here: https://erdantic.drivendata.org/v1.0/customizing/
