### ISSUE TITLE
Support for pydbantic

### ISSUE THREAD

**Issue by cmarkle85** [drivendataorg/erdantic#79]
[pydbantic](https://github.com/codemation/pydbantic )

**Comment by jayqi** [comment]
Hi @cmarkle85, curious if you've already tried using it and what broke? Since pydbantic's `DataBaseModel` is a subclass of pydantic's `BaseModel`, I think erdantic would try to do _something_ as if it were just dealing with regular pydantic models.

**Comment by jayqi** [comment]
Closing as stale. Can reopen if additional details are provided.
