### ISSUE TITLE
Allow user to provide custom cardinality and modality

### ISSUE THREAD

**Issue by ion-elgreco** [drivendataorg/erdantic#88]
I was playing around with erdantic, but I could not get satisfactory results that would give me a proper ERD. I've built some helper scripts where I can create an ERD from a Patito model (pydantic for Polars dataframes). 

The issue is that Erdantic assumes the cardinality based on the field type. So a string or int will become 1:1 or 0:1 relationship, and only a List(string) will get the many relationshpi. But this is in many cases wrong, a table can have multiple records where it can match with that foreign key even if the type is just string or int. It would be very useful in some cases to provide the cardinality myself.  

I will open a PR for this, and give it a try to change the behaviour, by allowing additional fields in the Edge class.

**Comment by jayqi** [comment]
Hi @ion-elgreco,

v1.0.0 is available as a pre-release version (v1.0.0rc1). You can install it with `pip install erdantic --pre`. I'd appreciate your testing and feedback on whether it meets your needs.  

Here is the documentation about how to modify the cardinality and modality of the edges in the diagram data: https://erdantic.drivendata.org/v1.0/customizing/#customizing-diagram-content
