### ISSUE TITLE
Create edges with modality and cardinality on left and right-hand side

### ISSUE THREAD

**Issue by ion-elgreco** [drivendataorg/erdantic#91]
Currently, when you set edges, you only set the cardinality/modality for the source model but there should be a way to set the target cardinality and modality as well in this edge.

Providing an additional edge from target-to-source doesn't really work:

![image](https://github.com/drivendataorg/erdantic/assets/15728914/6c043371-5f5b-4aff-bb52-be4716bd861f)

**Comment by jayqi** [comment]
Hi @ion-elgreco,

v1.0.0 is available as a pre-release version (v1.0.0rc1). You can install it with `pip install erdantic --pre`. I'd appreciate your testing and feedback on whether it meets your needs.  

There are now fields on the `Edge` object called `source_cardinality` and `source_modality` where the values are expected to be enum values. By default, these are set to `Cardinality.UNSPECIFIED` and `Modality.UNSPECIFIED`, respectively. You can manually update `Edge` instances to set them to other values. Here is the documentation about how to modify the cardinality and modality of the edges in the diagram data: https://erdantic.drivendata.org/v1.0/customizing/#customizing-diagram-content
