### ISSUE TITLE
List Relationships not represented correctly

### ISSUE THREAD

**Issue by otyrrell** [drivendataorg/erdantic#93]
When using erdantic with pydantic model, the one to many relationships are not rendered properly

As shown below the erdantic examples work as expected, however the simple example I have shown is not rendered correctly. I can't see the difference between the A class I have written and the party example. Any help much appreciated!

```
import erdantic as erd
from erdantic.examples.pydantic import Party

# Easy one-liner
erd.draw(Party, out="diagram.png")


class B(BaseModel):
    """
    B Class
    """

    id: str


class A(BaseModel):
    """
    A Class
    """

    list_b: List[B]


erd.draw(A, out="A.jpg")
```

![diagram](https://github.com/drivendataorg/erdantic/assets/60891015/63ae9c22-893a-4f7a-b040-52e828ef128e)
![A](https://github.com/drivendataorg/erdantic/assets/60891015/7ba0fa18-9697-4783-bd1e-257cece16b01)

**Comment by otyrrell** [comment]
Sorry, I didn't copy the full code, please see full segment below:
```
import erdantic as erd
from erdantic.examples.pydantic import Party
from typing import List
from pydantic import BaseModel

# Easy one-liner
erd.draw(Party, out="diagram.png")


class B(BaseModel):
    """
    B Class
    """

    id: str


class A(BaseModel):
    """
    A Class
    """

    list_b: List[B]


erd.draw(A, out="A.jpg")
result = erd.create(A).to_dot()
print(result)
```

This provides the output:

```
digraph "Entity Relationship Diagram" {
        graph [fontcolor=gray66,
                fontsize=9,
                label="Created by erdantic v0.6.0 <https://github.com/drivendataorg/erdantic>",
                nodesep=0.5,
                rankdir=LR,
                ranksep=1.5
        ];
        node [fontsize=14,
                label="\N",
                shape=plain
        ];
        "__main__.A"    [label=<<table border="0" cellborder="1" cellspacing="0"><tr><td port="_root" colspan="2"><b>A</b></td></tr><tr><td>list_b</td><td port="list_b">List[B]</td></tr></table>>,
                tooltip="__main__.A&#xA;&#xA;A Class&#xA;"];
        "__main__.B"    [label=<<table border="0" cellborder="1" cellspacing="0"><tr><td port="_root" colspan="2"><b>B</b></td></tr><tr><td>id</td><td port="id">str</td></tr></table>>,
                tooltip="__main__.B&#xA;&#xA;B Class&#xA;"];
        "__main__.A":list_b:e -> "__main__.B":_root:w   [arrowhead=crowodot];
}
```


Name: erdantic
Version: 0.6.0
Name: pydantic
Version: 2.3.0
Name: pygraphviz
Version: 1.11
GraphViz version 9.0.0 on Windows 10 x64


Only other thing I found is that it seems very specific to crow notation; when I changed "crow" to "icurve" on line 55 in erd.py it all works as expected (although showing the curve notation not the required crows foot)

**Comment by otyrrell** [comment]
Thank you for clarifying. I agree it does appear to be some sort of bug/unexpected behaviour within pygraphviz/graphviz. I couldn't find any relevant reports of crow foot notation having issues. I guess next step is understanding whether it is in the graphviz or the pygraphviz layer?

**Comment by jayqi** [comment]
I'm not seeing this anymore with `pygraphviz 1.12`, `graphviz 9.0.0`. Closing as resolved unless there are additional details provided.
